// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SetMovieModelProperties : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SetMovieModelProperties));
        
        string IMigrationMetadata.Id
        {
            get { return "201904060525292_SetMovieModelProperties"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
